import { Dimensions } from "react-native";
import { dynamicSize } from "../utils/dimension.style.js";
const { width, height } = Dimensions.get("window");

export const COLORS = {
    lightBlueNew2:"#316BCC",
    yellowNew:"#FFCF5F",
    yellowNew2:"#FFAC2E",
    skyBlueNew2:"#4181EF",
    skyBlueNew:'#EDF7FF',
    lightGreenNew: '#E6EBEE',
    CardBackgroundNew: '#EDF2F5',
    ViewBackgroundColorNew: '#F6F8FA',
    DarkBlueNew: '#2E4B74',
    lightPinkNew: '#FF8787',
    lightBlueNew: '#2E8DD7',
    lightGreenNew: '#E6EBEE',
    CardBackgroundNew: '#EDF2F5',
    ViewBackgroundColorNew: '#F6F8FA',
    DarkBlueNew: '#2E4B74',
    lightPinkNew: '#FF8787',
    lightBlueNew: '#2E8DD7',
    hdRed:'#F55944',
    darkblue3:'#2C599D',
    darkBlack:'#393939',
    hdRed:'#F55944',
    darkblue3:'#2C599D',
    green0:'#4BB543',
    orange:'#FF9C40',
    primary: "#fd8640",     // Orange
    primary2: "#3176EC",    // Blue
    primary3: "#274878",
    primary4:'#50BCFF',
    primary5:'#2B5796',   // Dark Blue
    primary6:'#2982C7',
    primary7:'#169CEF4D',
    primary8:'#3574DE',
    secondary: "#FC2626",   // Red
    lightGreen: '#81C9AD',
    darkGreen:'#00668b',
    green:'#3F815D',
    lightPink:'#FFDEDC',
    LightPink1:'#F8F8F8',
    chartBg: '#f5fcff',
    shadow: '#00000010',
    gray:'grey',
    gray1: '#888888',
    lightgrey: '#B9B9B9',
    lightgrey1: '#DBDBDB',
    lightGray2:'#DDDDDD',
    lightgrey3:'#7E7E7E',
    lightgrey4:'#ECECEC',
    gray5:'#EDF2F8',
    gray6:'#646464',
    gray8:'#DFDFDF',
    gray10: "#E5E5E5",
    gray15:'#F1F1F1',
    gray20: "#C4C4C4",
    gray25:'#B7B7B7',
    gray30: "#A1A1A1",
    gray40: "rgba(0, 0, 0, 0.3)",
    gray50: "#7F7F7F",
    gray60: "#666666",
    gray61: "#6A6A6A",
    gray70: "#4C4C4C",
    gray80: "#333333",
    gray85: "#242526",
    gray90: "#191919",
    gray100:"#424242",
    grayblue: "#C3D5EF",
    gray100: "#747F88",
    gray101:"#9AADBC5C",
    darkGray:'#858585',
    grey5:'#E9E9E9',
    grey6:'#8B8B8B',
    grey7:'#838383',
    gray8:'#f0f0f3',
    gray9:'#F2F2F2',
    gray10:'#C5C5C5',
    grey11:'#949494',
    gray2:'#696969',
    gray3:'#EBEBEB',
    darkgrey4:'#4A4A4A',
    lightGray3:'#EEEEEE',
    green_success: '#51D18C',
    red_failed:'#cc0000',
    pending:'#FFA959',
    additionalColor4: "#C3C3C3",
    additionalColor9: "#F3F3F3",
    additionalColor10: "#F0F0F0",
    additionalColor11: "#F0FFFB",
    additionalColor13: "#EBF3EF",
    additionalColor15:'#E6E6E6',
    additionalColor17:'#EFEFEF',
    background:'#F5F8FA',
    purple:'#8F76FF',
    lightPurple:'#F1EBFF',
    darkpurple:'#795EF2',
  
    pendingYellow:'#F9CC2D',
    yellow:'#FFA047',
    white: '#FFFFFF',
    black: "#212529",
    black1:'#494949',
    black2:'#3D3D3D',
    neutralBlack:'#09101D',
    indicatorColor: '#3235fd',

    lightSkyBlue:'#F9F9F9',

    lightYellow: '#FCF3D7',
    darkYellow: '#F4E9C8',

    lightRed: '#FFE0DE',
    lightRed1:'#FF7474',
    lightRed2:'#FFE8E9',
    lightRed3:'#FFE2E3',
    lightPink:'#FEF0F1',
    darkRed: '#F9D2D1',
    dardRed1:'#D44459',
    red: '#FF0000',
    red1:'#FF4F68',
    red2:'#FF767B',
    tomatoRed:'#F55944',
    red2:'#FF6666',
    red3:'#FF6568',
    borderColor:"#BDBDBD",
    darkgrey3: '#565656',
    darkgrey4: '#616161',

    skyBlue:'#F2F7FF',
    skyBlue1:'#0076BF',
    skyBlue2:'#4181EF',
    skyBlue3:'#E9F5FF',
    skyBlue4:'#0E56A9',
    skyBlue5:'#DBE7FB',
    lightBlue: '#D7DFFF',
    lightBlue1:'#EDF2F8',
    lightBlue2:'#DFF2FF',
    lightBlue3:'#A3DCFF',
    lightBlue4:'#C5D8EC',
    // lightBlue5:'#0076BF4D',
    lightBlue6:'#5F8ED2',
    lightBlue7:'#EEF7FD',
    darkBlue: '#D3D8FC',
    darkBlue1:'#2B5796',
    darkBlue2:'#004DBE',
    darkBlue3:'#2E4B74',
    darkBlue4:'#2F6DD7',
    lightBlue4:'#00B0BF',
    lightBlue5:'#3176EC',
    lightBlue: '#E9F6FF',
    dotColor1: '#ffffff',
    dotColor2: '#fd8640',

    transparent: 'transparent',
    transparentWhite1: "rgba(255, 255, 255, 0.1)",
    transparentBlack1: "rgba(0, 0, 0, 0.1)",
    transparentBlack8: "rgba(0, 0, 0, 0.8)",
    transparentBlack4: "rgba(0, 0, 0, 0.4)"
};
export const SIZES = {
    // global sizes
    base: dynamicSize(8),
    font: dynamicSize(14),
    radius: dynamicSize(4),
    padding: dynamicSize(24),
    margin: dynamicSize(12),

    // font sizes
    largeTitle: dynamicSize(32), 
    h1: dynamicSize(30),
    h2: dynamicSize(22),
    h3: dynamicSize(18),
    h4: dynamicSize(16),
    h5: dynamicSize(14),
    h6: dynamicSize(12),
    h7: dynamicSize(10),
    h8:dynamicSize(8),
    h9:dynamicSize(6),
    body1: dynamicSize(30),
    body2: dynamicSize(22),
    body3: dynamicSize(18),
    body4: dynamicSize(16),
    body5: dynamicSize(14),
    body6: dynamicSize(12),
    body7: dynamicSize(10),
    body8:dynamicSize(8),
    body9:dynamicSize(6),

    // app dimensions
    width,
    height
};
export const FONTS = {
    largeTitle: { fontFamily: "Roboto-Black", fontSize: SIZES.largeTitle },
    h1: { fontFamily: "Roboto-Black", fontSize: SIZES.h1, lineHeight: dynamicSize(36) },
    h2: { fontFamily: "Roboto-Bold", fontSize: SIZES.h2, lineHeight: dynamicSize(30) },
    h3: { fontFamily: "Roboto-Bold", fontSize: SIZES.h3, lineHeight: dynamicSize(22) },
    h4: { fontFamily: "Roboto-Bold", fontSize: SIZES.h4, lineHeight: dynamicSize(22) },
    h5: { fontFamily: "Roboto-Bold", fontSize: SIZES.h5, lineHeight: dynamicSize(22) },
    body1: { fontFamily: "Roboto-Regular", fontSize: SIZES.body1, lineHeight: dynamicSize(36) },
    body2: { fontFamily: "Roboto-Regular", fontSize: SIZES.body2, lineHeight: dynamicSize(36) },
    body3: { fontFamily: "Roboto-Regular", fontSize: SIZES.body3, lineHeight: dynamicSize(23) },
    body4: { fontFamily: "Roboto-Regular", fontSize: SIZES.body4, lineHeight: dynamicSize(22) },
    body5: { fontFamily: "Roboto-Regular", fontSize: SIZES.body5, lineHeight: dynamicSize(22) },
    body6: { fontFamily: "Roboto-Regular", fontSize: SIZES.body6, lineHeight: dynamicSize(20) },
    body7: { fontFamily: "Roboto-Regular", fontSize: SIZES.body7, lineHeight: dynamicSize(18) },
    body8: { fontFamily: "Roboto-Regular", fontSize: SIZES.body8, lineHeight: dynamicSize(12) },
    body9: { fontFamily: "Roboto-Regular", fontSize: SIZES.body9, lineHeight: dynamicSize(10) },
    toastFont: { fontFamily: "Roboto-Regular", fontSize: SIZES.body4},
};

export const darkTheme = {
    name: "dark",
    backgroundColor1: COLORS.gray85,
    backgroundColor2: COLORS.gray90,
    backgroundColor3: COLORS.gray90,
    backgroundColor4: COLORS.primary,
    backgroundColor5: COLORS.gray85,
    backgroundColor6: COLORS.black,
    backgroundColor7: COLORS.gray90,
    backgroundColor8: COLORS.gray70,
    backgroundColor9: COLORS.black,
    backgroundColor10: COLORS.gray70,
    backgroundColor11: COLORS.gray70,
    backgroundColor12: COLORS.gray85,
    backgroundColor13: COLORS.gray70,
    lineDivider: COLORS.gray70,
    borderColor1: COLORS.gray70,
    borderColor2: COLORS.gray70,
    textColor: COLORS.white,
    textColor2: COLORS.white,
    textColor3: COLORS.gray40,
    textColor4: COLORS.white,
    textColor5: COLORS.gray30,
    textColor6: COLORS.gray30,
    textColor7: COLORS.gray40,
    tintColor: COLORS.white,
    dotColor1: COLORS.white,
    dotColor2: COLORS.primary,
}

export const lightTheme = {
    name: "light",
    backgroundColor1: COLORS.white,
    backgroundColor2: COLORS.primary3,
    backgroundColor3: COLORS.additionalColor11,
    backgroundColor4: COLORS.white,
    backgroundColor5: COLORS.additionalColor13,
    backgroundColor6: COLORS.primary3,
    backgroundColor7: COLORS.white,
    backgroundColor8: COLORS.gray10,
    backgroundColor9: COLORS.primary3,
    backgroundColor10: COLORS.additionalColor13,
    backgroundColor11: COLORS.additionalColor11,
    backgroundColor12: COLORS.lightBlue,
    backgroundColor13: COLORS.primary3,
    backgroundColor14:COLORS.skyBlue,
    lineDivider: COLORS.gray20,
    borderColor1: COLORS.white,
    borderColor2: COLORS.black,
    textColor: COLORS.black,
    textColor2: COLORS.primary,
    textColor3: COLORS.gray80,
    textColor4: COLORS.white,
    textColor5: COLORS.black,
    textColor6: COLORS.gray,
    textColor7: COLORS.black,
    tintColor: COLORS.black,
    dotColor1: COLORS.gray20,
    dotColor2: COLORS.primary3,
   
}

export const selectedTheme = lightTheme

const appTheme = { COLORS, SIZES, FONTS, darkTheme, lightTheme };

export default appTheme;
